### ISSUE TITLE
TSQL is Modified by Data Set Creation Wizard

### ISSUE THREAD

**Issue by fore0054** [dashbuilder/dashbuilder#27]
When using the Data Set Creation Wizard the TSQL Submitted is modified, including the addition of the limit parameter.  When Using MS SQLServer this causes the query to fail.

Connections to MSSQL will succeed with the JDBC driver but cannot be created in the Wizard.  Perhaps a Check Box for or Drop Down allowing the user to select their flavor of SQL could allow the query modification to be tailored to that DB.

**Comment by dgutierr** [comment]
We have recently pushed to master a new implementation of the SQL provider which removes any dependency to the jooq library. We have added a full battery of unit tests including automated tests against SQL server 2012 & 2014. 

You should not have any issues when creating your custom queries on SQL server. It's true the final queries executed by the dashbuilder SQL engine are modified versions of the original query, this is necessary in order to add the group, filter and sort operations defined by the data set lookup calls, including the initial filters defined at a data set level.

Please give the latest sources on master a try and let us know if everything works as expected against SQL server.
